pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
rootProject.name="agp9_experiment"
plugins {
    id("com.gradle.develocity") version "4.1"
    id("com.gradle.common-custom-user-data-gradle-plugin") version "2.2"
    
}

develocity {
    server = "https://ge.solutions-team.gradle.com/"
    allowUntrustedServer = true
    buildScan {
        uploadInBackground.set(false)
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
} 
include (":core:push")
include (":core:contact")
include (":core:login")
include (":core:identity")
include (":core:checkout")
include (":core:cart")
include (":core:user")
include (":feature:profile")
include (":feature:feed")
include (":feature:comment")
include (":feature:post")
include (":feature:search")
include (":feature:location")
include (":feature:network")
include (":feature:sync")
include (":feature:share")
include (":domain:group")
include (":domain:message")
include (":domain:notification")
include (":domain:setting")
include (":domain:account")
include (":domain:session")
include (":domain:analytics")
include (":domain:report")
include (":domain:log")
include (":domain:status")
include (":domain:metric")
include (":domain:task")
include (":domain:calendar")
include (":domain:event")
include (":repository:alarm")
include (":repository:timer")
include (":repository:file")
include (":repository:document")
include (":repository:note")
include (":repository:todo")
include (":repository:list")
include (":repository:map")
include (":repository:weather")
include (":repository:forecast")
include (":repository:news")
include (":repository:article")
include (":repository:podcast")
include (":repository:video")
include (":repository:photo")
include (":repository:gallery")
include (":repository:media")
include (":repository:audio")
include (":repository:playlist")
include (":repository:push-contact")
include (":repository:contact-contact")
include (":repository:login-contact")
include (":repository:identity-contact")
include (":repository:checkout-contact")
include (":repository:cart-contact")
include (":repository:user-contact")
include (":repository:profile-contact")
include (":repository:feed-contact")
include (":repository:comment-contact")
include (":model:post-contact")
include (":entity:search-contact")
include (":entity:location-contact")
include (":entity:network-contact")
include (":entity:sync-contact")
include (":entity:share-contact")
include (":data:group-contact")
include (":data:message-contact")
include (":data:notification-contact")
include (":data:setting-contact")
include (":data:account-contact")
include (":data:session-contact")
include (":api:analytics-contact")
include (":api:report-contact")
include (":api:log-contact")
include (":api:status-contact")
include (":api:metric-contact")
include (":api:task-contact")
include (":api:calendar-contact")
include (":api:event-contact")
include (":api:alarm-contact")
include (":presentation:timer-contact")
include (":presentation:file-contact")
include (":presentation:document-contact")
include (":presentation:note-contact")
include (":presentation:todo-contact")
include (":presentation:list-contact")
include (":presentation:map-contact")
include (":presentation:weather-contact")
include (":presentation:forecast-contact")
include (":presentation:news-contact")
include (":presentation:article-contact")
include (":presentation:podcast-contact")
include (":presentation:video-contact")
include (":ui:photo-contact")
include (":ui:gallery-contact")
include (":ui:media-contact")
include (":ui:audio-contact")
include (":ui:playlist-contact")
include (":ui:push-login")
include (":ui:contact-login")
include (":ui:login-login")
include (":ui:identity-login")
include (":ui:checkout-login")
include (":ui:cart-login")
include (":ui:user-login")
include (":ui:profile-login")
include (":ui:feed-login")
include (":ui:comment-login")
include (":ui:post-login")
include (":ui:search-login")
include (":ui:location-login")
include (":ui:network-login")
include (":ui:sync-login")
include (":ui:share-login")
include (":ui:group-login")
include (":ui:message-login")
include (":ui:notification-login")
include (":ui:setting-login")
include (":ui:account-login")
include (":app:app")