plugins {
    id("awesome.androidapp.plugin")
}

dependencies {
    implementation(project(":ui:photo-contact"))
    implementation(project(":ui:gallery-contact"))
    implementation(project(":ui:media-contact"))
    implementation(project(":ui:audio-contact"))
    implementation(project(":ui:playlist-contact"))
    implementation(project(":ui:push-login"))
    implementation(project(":ui:contact-login"))
    implementation(project(":ui:login-login"))
    implementation(project(":ui:identity-login"))
    implementation(project(":ui:checkout-login"))
    implementation(project(":ui:cart-login"))
    implementation(project(":ui:user-login"))
    implementation(project(":ui:profile-login"))
    implementation(project(":ui:feed-login"))
    implementation(project(":ui:comment-login"))
    implementation(project(":ui:post-login"))
    implementation(project(":ui:search-login"))
    implementation(project(":ui:location-login"))
    implementation(project(":ui:network-login"))
    implementation(project(":ui:sync-login"))
    implementation(project(":ui:share-login"))
    implementation(project(":ui:group-login"))
    implementation(project(":ui:message-login"))
    implementation(project(":ui:notification-login"))
    implementation(project(":ui:setting-login"))
    implementation(project(":ui:account-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    ksp(libs.hilt.compiler.androidx)
    ksp(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)
    kspAndroidTest(libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}